
travel_emails_config.settings_form:
  path: '/admin/config/travel_emails_config/settings'
  defaults:
    _form: '\Drupal\travel_emails_config\Form\SettingsForm'
    _title: 'SettingsForm'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE

